Expand docstring for vmap with details about out_axes, and improve error checking
The newly added test cases used to raise the following kinds of exceptions:

AttributeError: 'float' object has no attribute 'shape'

ValueError: (0, None)

ValueError: vmap got inconsistent sizes for array axes to be mapped:
    arg 0 has shape (2,) and axis None is to be mapped
        so

TypeError: only integer scalar arrays can be converted to a scalar index.